server:
  port: 8080
  servlet:
    context-path: /app
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop7
    username: root
    password: admin
  #    driver-class-name: org.postgresql.Driver
  #    url: jdbc:postgresql://localhost:5432/shop7
  #    username: postgres
  #    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        dialect: org.hibernate.dialect.PostgreSQL94Dialect